/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as GrievancesRouteImport } from './routes/grievances'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminKbRouteImport } from './routes/admin.kb'
import { Route as AdminPolicyConflictsRouteImport } from './routes/admin.policy-conflicts'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsRequestIdRouteImport } from './routes/requests.$requestId'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffApprovalsRouteImport } from './routes/staff.approvals'
import { Route as StaffRequestsRouteImport } from './routes/staff.requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancesRoute = GrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKbRoute = AdminKbRouteImport.update({
  id: '/admin/kb',
  path: '/admin/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPolicyConflictsRoute = AdminPolicyConflictsRouteImport.update({
  id: '/admin/policy-conflicts',
  path: '/admin/policy-conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffApprovalsRoute = StaffApprovalsRouteImport.update({
  id: '/staff/approvals',
  path: '/staff/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRequestsRoute = StaffRequestsRouteImport.update({
  id: '/staff/requests',
  path: '/staff/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grievances': typeof GrievancesRoute
  '/labs': typeof LabsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/kb': typeof AdminKbRoute
  '/admin/policy-conflicts': typeof AdminPolicyConflictsRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/staff/approvals': typeof StaffApprovalsRoute
  '/staff/requests': typeof StaffRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grievances': typeof GrievancesRoute
  '/labs': typeof LabsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/kb': typeof AdminKbRoute
  '/admin/policy-conflicts': typeof AdminPolicyConflictsRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/staff/approvals': typeof StaffApprovalsRoute
  '/staff/requests': typeof StaffRequestsRoute
  '/admin': typeof AdminIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grievances': typeof GrievancesRoute
  '/labs': typeof LabsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/kb': typeof AdminKbRoute
  '/admin/policy-conflicts': typeof AdminPolicyConflictsRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/staff/approvals': typeof StaffApprovalsRoute
  '/staff/requests': typeof StaffRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/grievances'
    | '/labs'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/admin/audit'
    | '/admin/kb'
    | '/admin/policy-conflicts'
    | '/requests/$requestId'
    | '/staff/approvals'
    | '/staff/requests'
    | '/admin/'
    | '/requests/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/grievances'
    | '/labs'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/admin/audit'
    | '/admin/kb'
    | '/admin/policy-conflicts'
    | '/requests/$requestId'
    | '/staff/approvals'
    | '/staff/requests'
    | '/admin'
    | '/requests'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/grievances'
    | '/labs'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/admin/audit'
    | '/admin/kb'
    | '/admin/policy-conflicts'
    | '/requests/$requestId'
    | '/staff/approvals'
    | '/staff/requests'
    | '/admin/'
    | '/requests/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  GrievancesRoute: typeof GrievancesRoute
  LabsRoute: typeof LabsRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminKbRoute: typeof AdminKbRoute
  AdminPolicyConflictsRoute: typeof AdminPolicyConflictsRoute
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
  StaffApprovalsRoute: typeof StaffApprovalsRoute
  StaffRequestsRoute: typeof StaffRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievances': {
      id: '/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof GrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kb': {
      id: '/admin/kb'
      path: '/admin/kb'
      fullPath: '/admin/kb'
      preLoaderRoute: typeof AdminKbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/policy-conflicts': {
      id: '/admin/policy-conflicts'
      path: '/admin/policy-conflicts'
      fullPath: '/admin/policy-conflicts'
      preLoaderRoute: typeof AdminPolicyConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/approvals': {
      id: '/staff/approvals'
      path: '/staff/approvals'
      fullPath: '/staff/approvals'
      preLoaderRoute: typeof StaffApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/requests': {
      id: '/staff/requests'
      path: '/staff/requests'
      fullPath: '/staff/requests'
      preLoaderRoute: typeof StaffRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  GrievancesRoute: GrievancesRoute,
  LabsRoute: LabsRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminKbRoute: AdminKbRoute,
  AdminPolicyConflictsRoute: AdminPolicyConflictsRoute,
  RequestsRequestIdRoute: RequestsRequestIdRoute,
  StaffApprovalsRoute: StaffApprovalsRoute,
  StaffRequestsRoute: StaffRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
